[tool.poetry]
name = "aoc"
version = "0.1.0"
description = "Advent Of Code Solutions"
authors = ["brdv <brdv@pm.me>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
all = "aoc.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
